
class AllahName {
  final String name;
  final String translation;
  AllahName({required this.name, required this.translation});
}
final List<AllahName> allahNames = [
  AllahName(name: "الله", translation: "The God"),
  AllahName(name: "الرحمن", translation: "The Most Merciful"),
  AllahName(name: "الرحيم", translation: "The Most Compassionate"),
  AllahName(name: "الملك", translation: "The King"),
  AllahName(name: "القدوس", translation: "The Pure"),
  AllahName(name: "السلام", translation: "The Source of Peace"),
  AllahName(name: "المؤمن", translation: "The Giver of Security"),
  AllahName(name: "المهيمن", translation: "The Protector"),
  AllahName(name: "العزيز", translation: "The Mighty"),
  AllahName(name: "الجبار", translation: "The Compeller"),
  AllahName(name: "المتكبر", translation: "The Supreme"),
  AllahName(name: "الخالق", translation: "The Creator"),
  AllahName(name: "البارئ", translation: "The Evolver"),
  AllahName(name: "المصور", translation: "The Fashioner"),
  AllahName(name: "الغفار", translation: "The Great Forgiver"),
  AllahName(name: "القهار", translation: "The All-Prevailing One"),
  AllahName(name: "الوهاب", translation: "The Bestower"),
  AllahName(name: "الرزاق", translation: "The Provider"),
  AllahName(name: "الفتاح", translation: "The Opener, The Victory Giver"),
  AllahName(name: "العليم", translation: "The All-Knowing"),
  AllahName(name: "القابض", translation: "The Withholder"),
  AllahName(name: "الباسط", translation: "The Extender"),
  AllahName(name: "الخافض", translation: "The Abaser"),
  AllahName(name: "الرافع", translation: "The Exalter"),
  AllahName(name: "المعز", translation: "The Honourer"),
  AllahName(name: "المذل", translation: "The Dishonourer"),
  AllahName(name: "السميع", translation: "The All-Hearing"),
  AllahName(name: "البصير", translation: "The All-Seeing"),
  AllahName(name: "الحكم", translation: "The Judge"),
  AllahName(name: "العدل", translation: "The Just"),
  AllahName(name: "اللطيف", translation: "The Subtle One"),
  AllahName(name: "الخبير", translation: "The All-Aware"),
  AllahName(name: "الحليم", translation: "The Forbearing"),
  AllahName(name: "العظيم", translation: "The Magnificent"),
  AllahName(name: "الغفور", translation: "The Great Forgiver"),
  AllahName(name: "الشكور", translation: "The Most Appreciative"),
  AllahName(name: "العلي", translation: "The Most High"),
  AllahName(name: "الكبير", translation: "The Most Great"),
  AllahName(name: "الحفيظ", translation: "The Preserver"),
  AllahName(name: "المقيت", translation: "The Sustainer"),
  AllahName(name: "الحسيب", translation: "The Reckoner"),
  AllahName(name: "الجليل", translation: "The Majestic"),
  AllahName(name: "الكريم", translation: "The Most Generous"),
  AllahName(name: "الرقيب", translation: "The Watchful"),
  AllahName(name: "المجيب", translation: "The Responsive"),
  AllahName(name: "الواسع", translation: "The All-Encompassing"),
  AllahName(name: "الحكيم", translation: "The Most Wise"),
  AllahName(name: "الودود", translation: "The Most Loving"),
  AllahName(name: "المجيد", translation: "The Most Glorious"),
  AllahName(name: "الباعث", translation: "The Resurrector"),
  AllahName(name: "الشهيد", translation: "The Witness"),
  AllahName(name: "الحق", translation: "The Truth"),
  AllahName(name: "الوكيل", translation: "The Trustee"),
  AllahName(name: "القوي", translation: "The Most Strong"),
  AllahName(name: "المتين", translation: "The Firm"),
  AllahName(name: "الولي", translation: "The Guardian"),
  AllahName(name: "الحميد", translation: "The Praiseworthy"),
  AllahName(name: "المحصي", translation: "The Accounter"),
  AllahName(name: "المبدئ", translation: "The Originator"),
  AllahName(name: "المعيد", translation: "The Restorer"),
  AllahName(name: "المحيي", translation: "The Giver of Life"),
  AllahName(name: "المميت", translation: "The Creator of Death"),
  AllahName(name: "الحي", translation: "The Ever-Living"),
  AllahName(name: "القيوم", translation: "The Sustainer of All"),
  AllahName(name: "الواجد", translation: "The Perceiver"),
  AllahName(name: "الماجد", translation: "The Illustrious"),
  AllahName(name: "الواحد", translation: "The Unique"),
  AllahName(name: "الاحد", translation: "The One"),
  AllahName(name: "الصمد", translation: "The Eternal, Satisfier of Needs"),
  AllahName(name: "القادر", translation: "The All-Powerful"),
  AllahName(name: "المقتدر", translation: "The Creator of All Power"),
  AllahName(name: "المقدم", translation: "The Expediter"),
  AllahName(name: "المؤخر", translation: "The Delayer"),
  AllahName(name: "الأول", translation: "The First"),
  AllahName(name: "الأخر", translation: "The Last"),
  AllahName(name: "الظاهر", translation: "The Manifest"),
  AllahName(name: "الباطن", translation: "The Hidden"),
  AllahName(name: "الوالي", translation: "The Sole Governor"),
  AllahName(name: "المتعال", translation: "The Self-Exalted"),
  AllahName(name: "البر", translation: "The Source of All Goodness"),
  AllahName(name: "التواب", translation: "The Ever-Pardoning"),
  AllahName(name: "المنتقم", translation: "The Avenger"),
  AllahName(name: "العفو", translation: "The Pardoner"),
  AllahName(name: "الرؤوف", translation: "The Most Kind"),
  AllahName(name: "مالك الملك", translation: "Master of the Kingdom"),
  AllahName(name: "ذو الجلال والإكرام", translation: "Lord of Glory and Honour"),
  AllahName(name: "المقسط", translation: "The Equitable"),
  AllahName(name: "الجامع", translation: "The Gatherer"),
  AllahName(name: "الغني", translation: "The Self-Sufficient"),
  AllahName(name: "المغني", translation: "The Enricher"),
  AllahName(name: "المانع", translation: "The Preventer"),
  AllahName(name: "الضار", translation: "The Distresser"),
  AllahName(name: "النافع", translation: "The Propitious"),
  AllahName(name: "النور", translation: "The Light"),
  AllahName(name: "الهادي", translation: "The Guide"),
  AllahName(name: "البديع", translation: "The Incomparable"),
  AllahName(name: "الباقي", translation: "The Everlasting"),
  AllahName(name: "الوارث", translation: "The Inheritor"),
  AllahName(name: "الرشيد", translation: "The Guide to the Right Path"),
  AllahName(name: "الصبور", translation: "The Patient"),
];

